use image_storagedb;

CREATE TABLE project_1_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_2_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_3_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_4_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_5_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_6_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_7_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_8_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_9_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_10_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_11_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_12_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_13_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_14_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_15_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_16_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_17_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_18_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_19_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_20_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_21_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_22_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_23_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_24_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_25_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_26_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_27_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_28_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_29_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_30_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_31_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_32_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_33_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_34_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_35_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

CREATE TABLE project_36_record_history
(

guid BIGINT NOT NULL REFERENCES record_registry (guid),
client_name VARCHAR(64) NOT NULL,
client_version VARCHAR(20) NOT NULL,
modified_by VARCHAR(64) NOT NULL REFERENCES user_registry (user_login),
modification_time TIMESTAMP NOT NULL DEFAULT 0,
modification_type ENUM ('RECORD_CREATED', 'RECORD_DELETED', 'ADDED_CHILD_RECORD', 'ADDED_PARENT_RECORD', 'ATTACHMENT_ADDED', 'ATTACHMENT_DELETED', 'USER_ANNOTATION_ADDED', 'USER_ANNOTATION_DELETED', 'USER_ANNOTATION_MODIFIED', 'USER_COMMENT_ADDED', 'USER_COMMENT_DELETED', 'VISUAL_OVERLAY_ADDED', 'VISUAL_OVERLAY_DELETED', 'VISUAL_ANNOTATION_ADDED', 'VISUAL_ANNOTATION_DELETED', 'TASK_EXECUTED', 'TASK_TERMINATED', 'TASK_FAILED', 'TASK_SUCCESSFUL', 'CUSTOM_HISTORY') NOT NULL,
modification_description TEXT DEFAULT NULL,


INDEX(guid)
)engine=MyISAM;

