/**
 * openImaDis - Open Image Discovery: Image Life Cycle Management Software
 * Copyright (C) 2011-2016  Strand Life Sciences
 *   
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.strandgenomics.imaging.iengine.models;

import com.strandgenomics.imaging.icore.Storable;

public class VisualOverlay implements Storable {
	
	private static final long serialVersionUID = 3791963637251621355L;
	/**
	 * the frame number
	 */
	private int frameNo;
	/**
	 * the slice (Z) number
	 */
	private int sliceNo;
	/**
	 * the site number
	 */
	private int siteNo;
	/**
	 * width of the overlay
	 */
	private int width;
	/**
	 * height of the overlay
	 */
	private int height;
	/**
	 * name of the visual overlay
	 */
	private String name;
	/**
	 * if this visual overlay is created by user or generated by analysis application
	 */
	public final boolean handCreated;
	
	public VisualOverlay(int siteNo, String name, int width, int height, boolean handCreated)
	{
		this.siteNo = siteNo;
		this.name   = name;
		this.width  = width;
		this.height = height;
		this.handCreated = handCreated;
	}
	
	public int getSite()
	{
		return siteNo;
	}
	
	public int getFrame()
	{
		return frameNo;
	}
	
	public int getSlice()
	{
		return sliceNo;
	}
	
	public void setFrame(int value)
	{
		frameNo = value;
	}
	
	public void setSlice(int value)
	{
		sliceNo = value;
	}

	/**
	 * @return the width
	 */
	public int getWidth() 
	{
		return width;
	}
	/**
	 * @param width the width to set
	 */
	public void setWidth(int width)
{
		this.width = width;
	}
	/**
	 * @return the height
	 */
	public int getHeight() 
	{
		return height;
	}
	/**
	 * @param height the height to set
	 */
	public void setHeight(int height) 
	{
		this.height = height;
	}
	/**
	 * @return the name
	 */
	public String getName()
	{
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) 
	{
		this.name = name;
	}

	@Override
	public void dispose() 
	{}
}
