package com.strandgenomics.imaging.iacquisition;

/**
 * Fixed columns used in the spreadsheet
 * 
 * @author Anup Kulkarni
 */
public enum SpreadSheetFixedColumns {
	CREATION_TIME, ACQUIRED_DATE, UPLOAD_TIME, UPLOAD_STATUS, SERIES_NUMBER, SERIES_NAME, SLICE_COUNT, FRAME_COUNT, CHANNEL_COUNT, SITE_COUNT, IMAGE_WIDTH, IMAGE_HEIGHT, IMAGE_COUNT, PIXEL_DEPTH, PIXEL_SIZE_X, PIXEL_SIZE_Y, PIXEL_SIZE_Z, IMAGE_TYPE, SOURCE_TYPE, SOURCE_FILENAME, ROOT_DIRECTORY, MACHINE_IP, PROJECT_NAME
}
