package com.strandgenomics.imaging.iserver.services.def.ispace;

/**
 * different type of history items
 * 
 * @author Anup Kulkarni 
 */
public enum HistoryType {
	RECORD_CREATED,
	RECORD_DELETED,
	ADDED_CHILD_RECORD,
	ADDED_PARENT_RECORD,
	ATTACHMENT_ADDED,
	ATTACHMENT_DELETED,
	USER_ANNOTATION_ADDED,
	USER_ANNOTATION_DELETED,
	USER_ANNOTATION_MODIFIED,
	USER_COMMENT_ADDED,
	USER_COMMENT_DELETED,
	VISUAL_OVERLAY_ADDED,
	VISUAL_OVERLAY_DELETED,
	VISUAL_ANNOTATION_ADDED,
	VISUAL_ANNOTATION_DELETED,
	TASK_EXECUTED, 
	TASK_TERMINATED, 
	TASK_FAILED, 
	TASK_SUCCESSFUL
}
